apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: rabbitmq-imroc-io
  namespace: rabbitmq-server
spec:
  secretName: rabbitmq-imroc-io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - rabbitmq.52db.club
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: rabbitmq.52db.club
      http:
        paths:
          - backend:
              serviceName: rabbitmq-service
              servicePort: 31004
            path: /
  tls:
    - secretName: rabbitmq-imroc-io-tls
      hosts:
        - rabbitmq.52db.club